# Generated by Django 3.2.17 on 2025-03-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelstock',
            old_name='quantity',
            new_name='label_quantity_1',
        ),
        migrations.AddField(
            model_name='labelstock',
            name='has_two_labels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labelstock',
            name='label_quantity_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packedstock',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
