# Generated by Django 3.2.17 on 2025-03-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20250308_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkstock',
            old_name='name',
            new_name='bulk_name',
        ),
        migrations.RenameField(
            model_name='bulkstock',
            old_name='quantity',
            new_name='bulk_quantity',
        ),
        migrations.RenameField(
            model_name='labelstock',
            old_name='name',
            new_name='label_name',
        ),
    ]
