# Generated by Django 3.2.17 on 2023-04-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionsIndividual',
        ),
    ]
