# Generated by Django 3.2.17 on 2023-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('IE', 'Ireland')], max_length=20)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('dog_name', models.CharField(max_length=100)),
                ('dog_breed', models.CharField(max_length=100)),
                ('dog_age', models.CharField(max_length=100)),
                ('profile_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
