# Generated by Django 3.2.16 on 2023-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('times', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
