# Generated by Django 3.2.17 on 2023-02-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230209_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionsindividual',
            old_name='days',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='sessionsindividual',
            old_name='times',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.sessionsindividual'),
        ),
    ]
