# Generated by Django 3.2.17 on 2023-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20230209_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
