# Generated by Django 3.2.17 on 2023-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
