# Generated by Django 3.2.17 on 2023-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_ready',
            field=models.BooleanField(default=False),
        ),
    ]
