# Generated by Django 3.2.17 on 2023-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_profile_profile_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
