# Generated by Django 3.2.17 on 2023-02-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.profile'),
        ),
    ]
