# Generated by Django 3.2.17 on 2023-04-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20230227_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
