# Generated by Django 3.2.17 on 2023-04-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
